name:                lowarn-version-following-v1v0v0
version:             1.0.0
github:              "lowarn-dsu/lowarn"
license:             MIT
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

description:         Lowarn demo program 1

dependencies:
- base >= 4.7 && < 5
- lowarn
- lowarn-inject
- lowarn-transformer
- regex-tdfa ^>= 1.3.2

build-tools:
- lowarn-inject:lowarn-inject

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -F
- -pgmF=lowarn-inject
- -optF=following

flags:
  cabal:
    description: "The build system is Cabal if this flag is true."
    default: False
    manual: True

when:
  - condition: flag(cabal)
    ghc-options:
    - -plugin-package=lowarn-inject-0.1.0.0

library:
  source-dirs: src
