resolver: lts-20.13

packages:
- core
- examples/reproduction/demo
- examples/reproduction/updates/1.0.0-2.0.0
- examples/reproduction/versions/1.0.0
- examples/reproduction/versions/2.0.0
- runtime

ghc-options:
  "$everything": -rdynamic -fwhole-archive-hs-libs -fkeep-cafs -dynamic
  lowarn-version-reproduction-v1v0v0: -fno-keep-cafs
  lowarn-version-reproduction-v2v0v0: -fno-keep-cafs
  lowarn-update-reproduction-v1v0v0-v2v0v0: -fno-keep-cafs
