name:                lowarn-runtime
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Runtime system for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn/tree/main/runtime#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- free
- ghc == 9.2.5
- ghc-boot == 9.2.5
- ghc-paths
- ghci == 9.2.5
- Glob >= 0.10.2 && < 0.11
- lowarn
- transformers
- unix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
