name:                lowarn-runtime
version:             0.1.0.0
github:              "lowarn-dsu/lowarn"
license:             MIT
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Runtime system for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/lowarn-dsu/lowarn/tree/main/runtime#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- filepath
- ghc == 9.2.7
- ghc-boot == 9.2.7
- ghc-paths
- ghci == 9.2.7
- Glob >= 0.10.2 && < 0.11
- lowarn
- transformers
- unix

flags:
  dekking:
    description: "Dekking is used to find coverage when this flag is true."
    default: False
    manual: True

when:
  - condition: flag(dekking)
    dependencies:
    - dekking-plugin
    - dekking-value
    ghc-options:
    - -fplugin=Dekking.Plugin

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
