name:                reproduction
version:             1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

description:         Lowarn demo program

dependencies:
- base >= 4.7 && < 5
- lowarn
- lowarn-runtime

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  reproduction-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -rdynamic
    - -fkeep-cafs
    - -fwhole-archive-hs-libs
