name:                lowarn-cli
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Command-line interface for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn/tree/main/cli#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- Glob >= 0.10.2 && < 0.11
- lowarn
- lowarn-aeson
- lowarn-runtime
- path >= 0.9.2 && < 0.10
- path-io >= 1.7.0 && < 1.8
- transformers
- yaml >= 0.11.8 && < 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - lowarn-cli
  - optparse-applicative >= 0.17 && < 0.18
