name:                lowarn-cli
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Command-line interface for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn/tree/main/cli#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- bytestring-strict-builder >= 0.4.5.6 && < 0.5
- containers
- cryptohash-sha256 >= 0.11.102.1 && < 0.12
- hex-text >= 0.1.0.8 && < 0.2
- lowarn
- lowarn-aeson
- lowarn-runtime
- path >= 0.9.2 && < 0.10
- path-io >= 1.7.0 && < 1.8
- process
- split
- text >= 1.2.5 && < 1.3
- transformers
- uri-bytestring >= 0.3.3.1 && < 0.4
- uri-bytestring-aeson >= 0.1.0.8
- yaml >= 0.11.8 && < 0.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

flags:
  dekking:
    description: "Dekking is used to find coverage when this flag is true."
    default: False
    manual: True

when:
  - condition: flag(dekking)
    dependencies:
    - dekking-plugin
    - dekking-value
    ghc-options:
    - -fplugin=Dekking.Plugin

library:
  source-dirs: src

executables:
  lowarn-cli:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -rdynamic
    dependencies:
    - lowarn-cli
    - optparse-applicative >= 0.17 && < 0.18
