name:                lowarn-transformer-manual-following-v2v0v0-v3v0v0
version:             1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

description:         Lowarn demo program transformer from version 2.0.0 to 3.0.0

dependencies:
- base >= 4.7 && < 5
- lowarn
- lowarn-version-manual-following-v2v0v0
- lowarn-version-manual-following-v3v0v0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
