name:                lowarn-arbitrary
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Arbitrary instances for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn/tree/main/arbitrary#readme>

dependencies:
- base >= 4.7 && < 5
- combinat >= 0.2.10
- lowarn
- QuickCheck >= 2.14 && < 3
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans

library:
  source-dirs: src
