name:                lowarn-test-types
version:             0.1.0.0
github:              "lowarn-dsu/lowarn"
license:             MIT
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Types for lowarn-test
category:            System

description:         Please see the README on GitHub at <https://github.com/lowarn-dsu/lowarn/tree/main/test-types#readme>

dependencies:
- base >= 4.7 && < 5
- lowarn
- lowarn-transformer

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
