name:                lowarn-transformer-following-v1v0v0-v2v0v0
version:             1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

description:         Lowarn demo program transformer from version 1.0.0 to 2.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- lowarn
- lowarn-plugin
- lowarn-version-following-v1v0v0
- lowarn-version-following-v2v0v0
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin Lowarn.Plugin

library:
  source-dirs: src
