name:                lowarn-transformer
version:             0.1.0.0
github:              "lowarn-dsu/lowarn"
license:             MIT
author:              "Jonathan Watson"
# maintainer:
copyright:           "2023 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            State transformer utilities for Lowarn
category:            System

description:         Please see the README on GitHub at <https://github.com/lowarn-dsu/lowarn/tree/main/transformer#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq >= 1.4
- generics-sop >= 0.5.1 && < 0.6
- lowarn

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

flags:
  dekking:
    description: "Dekking is used to find coverage when this flag is true."
    default: False
    manual: True

when:
  - condition: flag(dekking)
    dependencies:
    - dekking-plugin
    - dekking-value
    ghc-options:
    - -fplugin=Dekking.Plugin

library:
  source-dirs: src
