resolver: lts-20.13

extra-deps:
- ghc-tcplugin-api-0.10.0.0

packages:
- ../../core
- ../../inject
- ../../runtime
- ../../transformer
- updates/0-1.0.0
- updates/1.0.0-2.0.0
- updates/2.0.0-3.0.0
- versions/1.0.0
- versions/2.0.0
- versions/3.0.0
