name:                lowarn-version-custom-ffi-v1v0v0
version:             1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2023 Jonathan Watson"

description:         Lowarn demo program 1

dependencies:
- base >= 4.7 && < 5
- lowarn

extra-libraries:
- c
- crypt

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
