name:                lowarn-programs
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             BSD3
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn#readme>

dependencies:
- base >= 4.7 && < 5
- plugins >= 1.6
- containers
- ghc
- ghc-paths

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -dynamic
- -shared
# - -fPIC

library:
  source-dirs: src
